name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Publish Docker Image to GitHub Registry
        uses: TilBlechschmidt/gp-docker-action@v0.2-alpha
        with:
          github-token: ${{ github.token }}

          image-name: nginx

          image-tag: latest
