name: Docker Image CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: publihostcontainerregistry.azurecr.io
          username: fedi.jaadari@ipein.u-carthage.tn 
          password: 36B*etQxnf

      - run: |
          docker build . -t publihostcontainerregistry.azurecr.io/nginx:1.0.0
          docker push publihostcontainerregistry.azurecr.io/nginx:1.0.0
    
    
    
    
    
    
    
    
    
    
    
